data:
  symbol: QQQ
  raw_path: data/raw/QQQ_full.csv
  processed_path: data/processed/QQQ_full_processed.csv
  price_col: close

model:
  target_col: log_ret
  train_frac: 0.6
  n_iter: 100
  seed: 42