data:
  symbol: QQQ # Ticker symbol (e.g., 'QQQ')
  raw_path: data/raw/QQQ_full.csv # Path to raw data
  processed_path: data/processed/QQQ_full_processed.csv # Path to processed data
  price_col: close # Column name for price data

model:
  target_col: log_ret # Column name for returns (use log returns)
  train_frac: 0.6 # Fraction of data to use for training
  n_iter: 100 # Number of iterations for model fitting
  seed: 42 # Random seed for reproducibility and the meaning of life ;)

forecasting:
  n_steps: 1825 # Number of days to forecast
  n_sims: 100 # Number of simulations per day for forecasting